Ensure some default node packages are installed

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -330,6 +330,27 @@ function dotfiles-node {
             logSub "Installed $latestPkg"
         fi
     done
+
+    local desired_packages=(
+        eslint_d
+        prettier
+        yarn
+        neovim
+    )
+
+    for pkg in $desired_packages; do
+        npm ls -g --depth=0 $pkg > /dev/null 2>&1
+        if (( $? )); then
+            local out=""
+            out=$(npm install -g $pkg > /dev/null 2>&1 )
+            if (( $? )); then
+                err "Error installing $pkg"
+                err $out
+            else
+                logSub "Installed $pkg"
+            fi
+        fi
+    done
 }
 
 # Update tmux plugins
