Make tmux script cross-platform

diff --git a/bin/tmux b/bin/tmux
--- a/bin/tmux
+++ b/bin/tmux
@@ -1,9 +1,22 @@
 #!/bin/zsh
 
+local tmux_bin
+
+if [[ -x /usr/local/bin/tmux ]]; then
+	tmux_bin=/usr/local/bin/tmux
+elif [[ -x /usr/bin/tmux ]]; then
+	tmux_bin=/usr/bin/tmux
+elif [[ -x /bin/tmux ]]; then
+	tmux_bin=/bin/tmux
+else
+	echo "Can't find tmux binary"
+	exit 1
+fi
+
 # Load tmux through direnv to ensure it's not using a local environment
 # See https://github.com/direnv/direnv/wiki/Tmux
 if (( $+commands[direnv] )); then
-	direnv exec / /usr/local/bin/tmux $@
+	direnv exec / $tmux_bin $@
 else
-	/usr/local/bin/tmux $@
+	$tmux_bin $@
 fi
