Vimrc updates
* Formatting (tabs to spaces)
* Add local node_modules/.bin to path for YCM
* Reduce updatetime for UI responsiveness
* Use rg for grep
* Disable ALE
* Add git-gutter
* Add vim-lsp config (not currently enabled)

diff --git a/vim/vimrc b/vim/vimrc
--- a/vim/vimrc
+++ b/vim/vimrc
@@ -1,28 +1,42 @@
 " Check for vim-plug; install if missing
 let plugpath = expand('<sfile>:p:h') . '/autoload/plug.vim'
 if !filereadable(plugpath)
-	if executable('curl')
-		call system('curl -fLo ' . shellescape(plugpath) . ' --create-dirs ' . 
-			\ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim')
-		if v:shell_error
-			echo "Error downloading vim-plug. Please install it manually.\n"
-			exit
-		endif
-	else
-		echo "Unable to download vim-plug. Please install it manually or install curl.\n"
-		exit
-	endif
+    if executable('curl')
+        call system('curl -fLo ' . shellescape(plugpath) . ' --create-dirs ' . 
+            \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim')
+        if v:shell_error
+            echo "Error downloading vim-plug. Please install it manually.\n"
+            exit
+        endif
+    else
+        echo "Unable to download vim-plug. Please install it manually or install curl.\n"
+        exit
+    endif
 endif
 
 " Put all swap and undo files in a central location
 if exists('$CACHEDIR')
-	set directory=$CACHEDIR/vim/swap//
-	set undodir=$CACHEDIR/vim/undo//
-	set backupdir=$CACHEDIR/vim/backup//
+    set directory=$CACHEDIR/vim/swap//
+    set undodir=$CACHEDIR/vim/undo//
+    set backupdir=$CACHEDIR/vim/backup//
 
-	if !has('nvim')
-		set viminfo+=n$CACHEDIR/vim/viminfo
-	endif
+    if !has('nvim')
+        set viminfo+=n$CACHEDIR/vim/viminfo
+    endif
+endif
+
+
+" If we're in a git project and there's a node_modules/.bin in the project
+" root, add it to the beginning of the path so that it's apps will be used for
+" commands started by vim. In particular this is useful for YCM + TypeScript
+" since YCM doesn't automatically look for a local TypeScript install.
+let project_root=system('git rev-parse --show-toplevel 2> /dev/null')
+if !empty(project_root)
+    let project_root=substitute(project_root, '\n\+$', '', '')
+    let bindir=project_root . '/node_modules/.bin'
+    if !empty(glob(bindir))
+        let $PATH=bindir . ':' . $PATH
+    endif
 endif
 
 " Set the leader character
@@ -40,19 +54,20 @@ set smartcase                " ...unless the search is mixed case
 set nojoinspaces             " Only insert 1 space after a period when joining lines
 set nostartofline            " Don't move to the beginning of a line when jumping
 set number                   " Show line numbers
-set completeopt-=preview     " Don't show the preview window when completing		     
+set completeopt-=preview     " Don't show the preview window when completing             
 set scrolloff=5              " Give the cursor a 5 line margin when scrolling
 set shiftwidth=4             " Indent in 4-character wide chunks
 set showcmd                  " Show commands in the cmd area
 set tabstop=4                " Tabs are only 4 characters wide
 set formatoptions+=ron       " Automatically format comments and numbered lists
-set ruler				     " Show location info in statusline
-set nowrap				     " Don't wrap text by default
+set ruler                    " Show location info in statusline
+set nowrap                   " Don't wrap text by default
 set wildignorecase           " Case insensitive filename completion
 set lazyredraw               " Redraw less frequently
 set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
-  \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
-  \,sm:block-blinkwait175-blinkoff150-blinkon175
+    \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
+    \,sm:block-blinkwait175-blinkoff150-blinkon175
+set updatetime=100           " More responsive UI updates
 
 " Toggle cursor crosshairs
 map <silent> # :set cursorcolumn! cursorline!<CR>
@@ -83,18 +98,20 @@ map <silent> <Leader><Space> :nohlsearch<CR>
 
 " Show the syntax status of the character under the cursor
 map <silent> <Leader>h :echo "hi<" . 
-	\ synIDattr(synID(line("."),col("."),1),"name") 
-	\ . '> trans<'
-	\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
-	\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
+    \ synIDattr(synID(line("."),col("."),1),"name") 
+    \ . '> trans<'
+    \ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
+    \ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
 
 " Files and buffers
 map <Leader>f :find 
 map <silent> <Leader>b :ls<CR> 
 
 " Ag for grepping (https://github.com/ggreer/the_silver_searcher)
-if executable('ag')
-	set grepprg=ag\ --nogroup\ --nocolor
+if executable('rg')
+    set grepprg=rg\ --no-heading\ --color=never
+elseif executable('ag')
+    set grepprg=ag\ --nogroup\ --nocolor
 endif
 
 " Better start/end atching
@@ -102,86 +119,86 @@ runtime! macros/matchit.vim
 
 " Easier navigation of text files
 function! TextMode()
-	setlocal wrap linebreak nolist display+=lastline
-	map <buffer> <silent> k gk
-	map <buffer> <silent> j gj
-	map <buffer> <silent> 0 g0
-	map <buffer> <silent> $ g$
+    setlocal wrap linebreak nolist display+=lastline
+    map <buffer> <silent> k gk
+    map <buffer> <silent> j gj
+    map <buffer> <silent> 0 g0
+    map <buffer> <silent> $ g$
 endfunction
 
 " General autocommands
 augroup vimrc
-	autocmd!
+    autocmd!
 
-	" Make text files easier to work with
-	autocmd FileType text call TextMode()
-	autocmd FileType textile call TextMode()
-	autocmd FileType markdown call TextMode()
-	autocmd FileType html call TextMode()
+    " Make text files easier to work with
+    autocmd FileType text call TextMode()
+    autocmd FileType textile call TextMode()
+    autocmd FileType markdown call TextMode()
+    autocmd FileType html call TextMode()
 
-	" Wrap lines in quickfix windows
-	autocmd FileType qf setlocal wrap linebreak nolist breakindent breakindentopt=shift:2
+    " Wrap lines in quickfix windows
+    autocmd FileType qf setlocal wrap linebreak nolist breakindent breakindentopt=shift:2
 
-	" Always start at the top of git commit messages
-	autocmd FileType gitcommit call setpos('.', [0, 1, 1, 0])
+    " Always start at the top of git commit messages
+    autocmd FileType gitcommit call setpos('.', [0, 1, 1, 0])
 
-	" Close help files and quickfix panes on 'q'
-	autocmd FileType help nnoremap <buffer> <silent> q :bd<CR>
-	autocmd FileType qf nnoremap <buffer> <silent> q :bd<CR>
+    " Close help files and quickfix panes on 'q'
+    autocmd FileType help nnoremap <buffer> <silent> q :bd<CR>
+    autocmd FileType qf nnoremap <buffer> <silent> q :bd<CR>
 
-	" More predictable syntax highlighting
-	autocmd BufEnter * syntax sync fromstart
+    " More predictable syntax highlighting
+    autocmd BufEnter * syntax sync fromstart
 
-	" Automatically close preview windows after autocompletion
-	autocmd CompleteDone * pclose
+    " Automatically close preview windows after autocompletion
+    autocmd CompleteDone * pclose
 
-	" Identify files in a zsh/functions directory as zsh scripts
-	autocmd BufRead */zsh/functions/* set filetype=zsh
+    " Identify files in a zsh/functions directory as zsh scripts
+    autocmd BufRead */zsh/functions/* set filetype=zsh
 
-	" ejs is HTML
-	autocmd BufRead *.ejs set filetype=html
+    " ejs is HTML
+    autocmd BufRead *.ejs set filetype=html
 
-	" When editing a file, jump back to the last edited line if it makes sense
-	" to do so
-	autocmd BufReadPost *
-		\ if line("'\"") > 1 && line("'\"") <= line("$") |
-		\     execute "normal! g'\"" |
-		\ endif
+    " When editing a file, jump back to the last edited line if it makes sense
+    " to do so
+    autocmd BufReadPost *
+        \ if line("'\"") > 1 && line("'\"") <= line("$") |
+        \     execute "normal! g'\"" |
+        \ endif
 
-	" move line mappings
-	" ∆ is <A-j> on macOS
-	" ˚ is <A-k> on macOS
-	nnoremap ∆ :m .+1<cr>==
-	nnoremap ˚ :m .-2<cr>==
-	inoremap ∆ <Esc>:m .+1<cr>==gi
-	inoremap ˚ <Esc>:m .-2<cr>==gi
-	vnoremap ∆ :m '>+1<cr>gv=gv
-	vnoremap ˚ :m '<-2<cr>gv=gv
+    " move line mappings
+    " ∆ is <A-j> on macOS
+    " ˚ is <A-k> on macOS
+    nnoremap ∆ :m .+1<cr>==
+    nnoremap ˚ :m .-2<cr>==
+    inoremap ∆ <Esc>:m .+1<cr>==gi
+    inoremap ˚ <Esc>:m .-2<cr>==gi
+    vnoremap ∆ :m '>+1<cr>gv=gv
+    vnoremap ˚ :m '<-2<cr>gv=gv
 
-	" Use ;; to go to previous buffer
-	nnoremap <leader><leader> <C-^>
+    " Use ;; to go to previous buffer
+    nnoremap <leader><leader> <C-^>
 augroup END
 
 " Ale
 " ---------------------------------------------------------------------
 "  Rely on YCM for typescript linting
-let g:ale_linters = {
-\   'javascript': ['eslint'],
-\   'typescript': [],
-\   'go': ['gofmt', 'golint', 'go vet']
-\}
+" let g:ale_linters = {
+" \   'javascript': ['eslint'],
+" \   'typescript': [],
+" \   'go': ['gofmt', 'golint', 'go vet']
+" \}
 " let g:ale_fixers = {
-" 	\   'typescript': [ 'prettier' ],
-" 	\   'javascript': [ 'prettier' ],
-" 	\   'json': [ 'prettier' ],
-" 	\   'scss': [ 'prettier' ],
-" 	\   'stylus': [ 'prettier' ],
-" 	\}
+"     \   'typescript': [ 'prettier' ],
+"     \   'javascript': [ 'prettier' ],
+"     \   'json': [ 'prettier' ],
+"     \   'scss': [ 'prettier' ],
+"     \   'stylus': [ 'prettier' ],
+"     \}
 " let g:ale_javascript_prettier_use_local_config = 1
 
-let g:ale_change_sign_column_color = 1
-let g:ale_sign_error = '✖'
-let g:ale_sign_warning = '⚠'
+" let g:ale_change_sign_column_color = 1
+" let g:ale_sign_error = '✖'
+" let g:ale_sign_warning = '⚠'
 " map <silent> <Leader>t :ALEFix<cr>
 
 " EasyAlign
@@ -197,6 +214,13 @@ let g:tablabel=''
 " fzf
 " ---------------------------------------------------------------------
 let g:fzf_layout = { 'down': 10 }
+
+" git-gutter
+" ---------------------------------------------------------------------
+map <silent> <Leader>hl :GitGutterLineHighlightsToggle<cr>
+map <silent> <Leader>hs :GitGutterStageHunk<cr>
+map <silent> <Leader>hp :GitGutterPreviewHunk<cr>
+map <silent> <Leader>hn :GitGutterNextHunk<cr>
 
 " Go
 " ---------------------------------------------------------------------
@@ -223,19 +247,15 @@ let g:limelight_paragraph_span = 1
 " markdown
 " ---------------------------------------------------------------------
 let g:markdown_fenced_languages = [
-\	'html',
-\	'python',
-\	'sh',
-\	'js=javascript',
-\	'jsx=javascript.jsx',
-\	'ts=typescript',
-\	'tsx=typescript.tsx',
+\    'html',
+\    'python',
+\    'sh',
+\    'json',
+\    'js=javascript',
+\    'jsx=javascript.jsx',
+\    'ts=typescript',
+\    'tsx=typescript.tsx',
 \ ]
-
-" miniyank
-" ---------------------------------------------------------------------
-" map p <Plug>(miniyank-autoput)
-" map P <Plug>(miniyank-autoPut)
 
 " NERDTree
 " ---------------------------------------------------------------------
@@ -247,11 +267,11 @@ let g:NERDTreeDirArrowCollapsible = '▼'
 let g:NERDTreeRespectWildIgnore = 1
 
 function! ToggleNerdTree()
-	if @% != "" && (!exists("g:NERDTree") || (g:NERDTree.ExistsForTab() && !g:NERDTree.IsOpen()))
-		:NERDTreeFind
-	else 
-		:NERDTreeToggle
-	endif
+    if @% != "" && (!exists("g:NERDTree") || (g:NERDTree.ExistsForTab() && !g:NERDTree.IsOpen()))
+        :NERDTreeFind
+    else 
+        :NERDTreeToggle
+    endif
 endfunction
 
 map <silent> <Leader>n :call ToggleNerdTree()<CR>
@@ -259,45 +279,45 @@ map <silent> <Leader>n :call ToggleNerdTree()<CR>
 " Neovim
 " ---------------------------------------------------------------------
 if has('nvim')
-	set inccommand=nosplit       " Show live substitutions
+    set inccommand=nosplit       " Show live substitutions
 
-	" <Leader>e to escape into command mode in an nvim terminal
-	tnoremap <leader>e <C-\><C-n>
+    " <Leader>e to escape into command mode in an nvim terminal
+    tnoremap <leader>e <C-\><C-n>
 
-	" Always enter insert mode when switching to a terminal
-	autocmd BufWinEnter,WinEnter term://* startinsert
+    " Always enter insert mode when switching to a terminal
+    autocmd BufWinEnter,WinEnter term://* startinsert
 
-	" Tell Neovim.app which Python to use
-	if executable('/usr/local/bin/python2')
-		let g:python_host_prog='/usr/local/bin/python2'
-	endif
-	if executable('/usr/local/bin/python3')
-		let g:python3_host_prog='/usr/local/bin/python3'
-	endif
+    " Tell Neovim.app which Python to use
+    if executable('/usr/local/bin/python2')
+        let g:python_host_prog='/usr/local/bin/python2'
+    endif
+    if executable('/usr/local/bin/python3')
+        let g:python3_host_prog='/usr/local/bin/python3'
+    endif
 
-	" Note -- Don't enable termguicolors because it's all around better for
-	" neovim to use the existing terminal palette rather than managing its
-	" own. For example, when using the terminal palette we automatically get
-	" things like tmux pane focus dimming.
+    " Note -- Don't enable termguicolors because it's all around better for
+    " neovim to use the existing terminal palette rather than managing its
+    " own. For example, when using the terminal palette we automatically get
+    " things like tmux pane focus dimming.
 endif
 
 " tig
 " ---------------------------------------------------------------------
 if has('nvim')
-	function! s:tig()
-		let s:callback = {}
-		let current = expand('%')
+    function! s:tig()
+        let s:callback = {}
+        let current = expand('%')
 
-		function! s:callback.on_exit(job_id, code, event)
-			bw!
-		endfunction
+        function! s:callback.on_exit(job_id, code, event)
+            bw!
+        endfunction
 
-		below new
-		call termopen('tig status', s:callback)
-		startinsert
-	endfunction
+        below new
+        call termopen('tig status', s:callback)
+        startinsert
+    endfunction
 
-	command! Tig call s:tig()
+    command! Tig call s:tig()
 endif
 
 " undotree
@@ -307,14 +327,44 @@ nnoremap <Leader>u :UndotreeToggle<CR>
 " vim-autoprettier
 " --------------------------------------------------------------------- 
 let g:autoprettier_types = [
-	\ 'typescript',
-	\ 'javascript',
-	\ 'css',
-	\ 'markdown',
-	\ 'scss',
-	\ ]
+    \ 'typescript',
+    \ 'javascript',
+    \ 'css',
+    \ 'markdown',
+    \ 'scss',
+    \ ]
 let g:autoprettier_exclude = [
-	\ ]
+    \ ]
+
+" vim-lsp
+" --------------------------------------------------------------------- 
+if executable('typescript-language-server')
+    au User lsp_setup call lsp#register_server({
+    \ 'name': 'typescript-language-server',
+    \ 'cmd': {
+    \     server_info->[
+    \         &shell,
+    \         &shellcmdflag,
+    \         'typescript-language-server --stdio'
+    \     ]
+    \ },
+    \ 'root_uri':{
+    \     server_info->lsp#utils#path_to_uri(
+    \         lsp#utils#find_nearest_parent_file_directory(
+    \             lsp#utils#get_buffer_path(), 'tsconfig.json'
+    \         )
+    \     )
+    \ },
+    \ 'whitelist': [
+    \     'typescript',
+    \     'typescript.tsx',
+    \     'javascript',
+    \     'javascript.jsx'
+    \ ],
+    \ })
+endif
+let g:lsp_signs_enabled = 1
+let g:lsp_diagnostics_echo_cursor = 1
 
 " YouCompleteMe
 " --------------------------------------------------------------------- 
@@ -323,7 +373,7 @@ map <Leader>e :YcmDiags<CR>
 let g:ycm_error_symbol = '✖'
 let g:ycm_warning_symbol = '!!'
 function! s:CustomizeYcmLocationWindow()
-	10wincmd _
+    10wincmd _
 endfunction
 autocmd User YcmLocationOpened call s:CustomizeYcmLocationWindow()
 " auto-close the quickfix window when YCM opens it
@@ -344,16 +394,18 @@ Plug 'tpope/vim-repeat'                    " support for repeating mapped comman
 Plug 'tpope/vim-surround'                  " for manipulating parens and such
 Plug 'moll/vim-bbye'                       " Preserve layout when closing buffers
 Plug 'christoomey/vim-tmux-navigator'      " Easy movement between vim and tmux panes
-Plug 'w0rp/ale'                            " Asynchronous linting
+" Plug 'w0rp/ale'                            " Asynchronous linting
 Plug 'junegunn/vim-easy-align'             " Easy vertical alignment of code elements
 Plug 'junegunn/limelight.vim'              " Easy vertical alignment of code elements
 Plug 'mbbill/undotree'                     " Visualize the undo tree
-Plug 'jason0x43/vim-autoprettier'
-" Plug 'bfredl/nvim-miniyank'           " Block Cut-and-paste
+Plug 'prettier/vim-prettier'               " Format TS, JS, MD, and others
+Plug 'jason0x43/vim-autoprettier'          " Automatically run Prettier
+Plug 'airblade/vim-gitgutter'              " Show diff markers in sign column
+Plug 'jremmen/vim-ripgrep'                 " RipGrep for file searching
 
 " Completion
 if has('python') || has('python3')
-	Plug 'Valloric/YouCompleteMe'
+    Plug 'Valloric/YouCompleteMe'
 endif
 
 " File browsing
@@ -375,34 +427,32 @@ Plug 'dag/vim-fish', { 'for': 'fish' }
 Plug 'elzr/vim-json', { 'for': 'json' }
 Plug 'groenewege/vim-less', { 'for': 'less' }
 Plug 'rust-lang/rust.vim', { 'for': 'rust' }
-" Plug 'jason0x43/vim-js-indent', { 'for':  [ 'javascript', 'typescript', 'html', 'jsp' ] }
-" Plug 'jason0x43/vim-js-syntax', { 'for':  [ 'javascript', 'html' ] }
 Plug 'pangloss/vim-javascript', { 'for':  [ 'javascript', 'javascript.jsx', 'markdown' ] }
 Plug 'mxw/vim-jsx', {'for': [ 'javascript.jsx', 'markdown' ] } 
 Plug 'tpope/vim-markdown', { 'for': 'markdown' }
 Plug 'mzlogin/vim-markdown-toc', { 'for': 'markdown' }
 Plug 'tpope/vim-classpath', { 'for': 'java' }
 Plug 'wavded/vim-stylus', { 'for': 'stylus' }
-Plug 'prettier/vim-prettier'
+Plug 'dmix/elvish.vim'
+Plug 'vmchale/ion-vim'
 
 " Load the go plugin if go is available
 if executable('go')
-	Plug 'fatih/vim-go', { 'for': 'go' }
+    Plug 'fatih/vim-go', { 'for': 'go' }
 endif
 
 " Load the fzf plugin if fzf is available
-" if executable('fzf') && has('nvim') && !has('gui_running')
 if executable('fzf') && has('nvim')
-	Plug $FZF_PATH
-	Plug 'junegunn/fzf.vim'
+    Plug $FZF_PATH
+    Plug 'junegunn/fzf.vim'
 
-	" These mappings depend on the FZF plugin being loaded
-	map <silent> <Leader>f :Files<CR>
-	map <silent> <Leader>b :Buffers<CR>
-	" Show untracked files, too
-	map <silent> <Leader>g :GFiles --cached --others --exclude-standard<CR>
-	map <silent> <Leader>s :Snippets<CR>
-	map <silent> <Leader>l :BLines<CR>
+    " These mappings depend on the FZF plugin being loaded
+    map <silent> <Leader>f :Files<CR>
+    map <silent> <Leader>b :Buffers<CR>
+    " Show untracked files, too
+    map <silent> <Leader>g :GFiles --cached --others --exclude-standard<CR>
+    map <silent> <Leader>s :Snippets<CR>
+    map <silent> <Leader>l :BLines<CR>
 endif
 
 " Load all the plugins
